# Generated by Django 2.1.2 on 2018-11-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20181103_2045'),
    ]

    operations = [

    ]
