# Generated by Django 2.1.2 on 2018-11-04 17:22

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20181104_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=froala_editor.fields.FroalaField(verbose_name='текст'),
        ),
    ]
